version: '3'
services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "8198:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/.htpasswd:/etc/nginx/.htpasswd
      - ./nginx/html:/usr/share/nginx/html
    depends_on:
      - service1_instance1
      - service1_instance2
      - service1_instance3
      - control_service

  service1_instance1:
    build: ./service1
    environment:
      - SLEEP_DELAY=2
    container_name: service1_instance1

  service1_instance2:
    build: ./service1
    environment:
      - SLEEP_DELAY=2
    container_name: service1_instance2

  service1_instance3:
    build: ./service1
    environment:
      - SLEEP_DELAY=2
    container_name: service1_instance3

  service2:
    build: ./service2
    container_name: service2

  control_service:
    build: ./control_service
    container_name: control_service
